### ISSUE TITLE
argh.dispatching.dispatch( skip_unknown_args=True )  bug

### ISSUE THREAD

**Issue by faymek** [neithere/argh#149] opened 2021-11-02 08:42 UTC
https://github.com/neithere/argh/blob/dcd3253f2994400a6a58a700c118c53765bc50a4/argh/dispatching.py#L152

Python 3.8
`parser.parse_known_args` return a tuple of (Namespace, list), while `parser.parse_args` return a Namespace. Below is my modification:

```python
if skip_unknown_args:
    namespace_obj, _ = parser.parse_known_args(argv, namespace=namespace)
else:
    namespace_obj = parser.parse_args(argv, namespace=namespace)
```

**Comment by neithere** [comment] 2023-02-07 22:59
I believe this is a duplicate of #134, please reopen if not. Thanks!

**Closed by neithere** 2023-02-07 22:59 UTC
Labels: duplicate
