### ISSUE TITLE
More detailed signature inference with typing.get_type_hints

### ISSUE THREAD

**Issue by fakuivan** [neithere/argh#144] opened 2021-04-01 15:33 UTC
I really like the idea of this library, taking a function and turning it into something that can be used from the CLI with minimal repetition. I use type hints extensively as a way to document functions. Are there any plans or ideas on how this could be used to set argument types? I was thinking maybe ``typing.get_type_hints`` could be used to resolve types, it even works with forward references, additionally from this containers like ``Optional`` and ``Tuple`` could be translated into ``nargs`` and other parameters. Any input on this?

**Comment by neithere** [comment] 2021-04-15 11:33
Hey, thank you for your interest. You've perfectly captured the purpose of the library.

I like the ideas about `Optional` and `Tuple`. Could you please add some example cases (function signature → add_argument statement) to #107?

**Comment by neithere** [comment] 2021-04-15 17:41
Closing as a duplicate of #107.

**Closed by neithere** 2021-04-15 17:41 UTC
Labels: component-assembling, design
